version: "3.2"
services:
  apache:
    build: .docker/apache
    restart: always
    container_name: theflashapp_apache
    depends_on:
      - php
      - db
    networks:
      - frontend
      - backend
    volumes:
      - .:/var/www/html
    ports:
      - 4000:80
      - 443:443
    environment:
      WEB_PHP_SOCKET: "theflashapp_php:9000"
      WEB_DOCUMENT_ROOT: "/var/www/html"

  php:
    build: .docker/php7
    restart: always
    container_name: theflashapp_php
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    links:
      - db
    networks:
      - frontend
      - backend
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"

  db:
    image: mysql:5.7.27
    container_name: theflashapp_db
    ports:
      - 3306:3306
    networks:
      - frontend
      - backend
    volumes:
      - .docker/mysql/conf:/etc/mysql/conf.d
      - .docker/mysql/dump:/docker-entrypoint-initdb.d
      - .docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=theflashapp
      - MYSQL_DATABASE=theflashapp

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - frontend
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true
